import { TrendReport } from '../types';
import * as fs from 'fs';

export function generateMarkdown(report: TrendReport): string {
  const date = new Date(report.generatedAt).toLocaleString('ko-KR', {
    timeZone: 'Asia/Seoul',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  });

  const tableRows = report.topVideos
    .map(
      (v, i) =>
        `| ${i + 1} | ${v.trendLabel || '-'} | ${v.title.slice(0, 40)}${v.title.length > 40 ? '...' : ''} | ${v.channelTitle} | ${v.viewCount.toLocaleString()} | ${v.velocityScore.toLocaleString()} | ${v.duration} |`
    )
    .join('\n');

  const channelTable = report.channelStats
    .slice(0, 5)
    .map(
      (c) =>
        `| ${c.channelTitle} | ${c.subscriberCount.toLocaleString()} | ${c.totalViewCount.toLocaleString()} | ${c.videoCount.toLocaleString()} |`
    )
    .join('\n');

  return `# YouTube 트렌드 리포트
생성일: ${date} | 분석 키워드: **${report.keyword}**

---

## 🔥 이번 주 급상승 토픽

${report.trendingSummary}

---

## 📊 영상 순위 분석 (Top 10)

| 순위 | 트렌드 | 제목 | 채널 | 조회수 | 시간당 조회수 | 길이 |
|------|--------|------|------|--------|------------|------|
${tableRows}

---

## 💡 제목 패턴 인사이트

${report.titlePatterns}

---

## 📺 주요 채널 현황 (Top 5)

| 채널명 | 구독자 | 총 조회수 | 영상 수 |
|--------|--------|----------|--------|
${channelTable}

---

## 📝 채널별 콘텐츠 아이디어

${report.contentIdeas}

---
*Generated by YouTube Trend Research Agent v0.1*
`;
}

export function saveReport(report: TrendReport, outputPath: string): void {
  const markdown = generateMarkdown(report);
  fs.writeFileSync(outputPath, markdown, 'utf-8');
  console.log(`\n리포트 저장 완료: ${outputPath}`);
}
